### PR TITLE
optimize the code

### PR DESCRIPTION
**Pull request by khcrysalis**
increased compilation performance and made it run faster

### CODE REVIEW

**Comment by fridakitten** [comment]
I wont nuke my repo, bro

**Comment by circularsprojects** [comment]
LGTM :+1:

**Comment by khcrysalis** [comment]
I approve of this commit

**Comment by darwinx64** [comment]
lgtm

**Comment by vmfunc** [comment]
[373210369-1b8f349b-d97a-4421-9cf0-7e0d2a1df06a.webm](https://github.com/user-attachments/assets/c0ee9be8-6aef-4e37-8537-5fb6bf1b002b)

**Pull request closed without merging**
